############# English navigation ##############

# main menu
[[main]]
name = "Strona główna"
pageRef = "/"
weight = 1

[[main]]
name = "Tło"
pageRef = "/about"
weight = 2

[[main]]
name = "Scena"
pageRef = "/stage"
weight = 3

[[main]]
weight = 4
name = "Wizja"

[[main]]
parent = "Wizja"
name = "Wizja 0.1"
pageRef = "/vision01"

# footer menu
[[footer]]
name = "Tło"
pageRef = "/about"
weight = 1

[[footer]]
name = "Scena"
pageRef = "/stage"
weight = 2

[[footer]]
name = "Polityka prywatności"
pageRef = "/privacy-policy"
weight = 3
