############# English navigation ##############

# main menu
[[main]]
name = "Strona główna"
pageRef = "/"
weight = 1

[[main]]
name = "Tło projektu"
pageRef = "/about"
weight = 2

[[main]]
name = "Rekrutacja"
pageRef = "/hiring"
weight = 3

# footer menu
[[footer]]
name = "Tło projektu"
pageRef = "/about"
weight = 1

[[footer]]
name = "Rekrutacja"
pageRef = "/hiring"
weight = 2

[[footer]]
name = "Polityka prywatności"
pageRef = "/privacy-policy"
weight = 3
