############# English navigation ##############

# main menu

[[main]]
name = "Program"
pageRef = "/program"
weight = 1

[[main]]
name = "Newsletter"
pageRef = "/newsletter"
weight = 2

[[main]]
name = "Blog"
pageRef = "/blog"
weight = 3


[[footer]]
name = "Privacy policy"
pageRef = "/privacy-policy"
weight = 1
